name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias
  workflow_dispatch:  # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: beatriz-duarte13  # Seu nome de usuário
          output: dist/snake.svg  # Salva o arquivo gerado

      - name: Push Snake Game to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # Diretório com o arquivo gerado
          destination_branch: output  # Define a branch de destino
